### ISSUE TITLE
[資料異動登載] 周汰南

### ISSUE THREAD

**Issue by mmmt0313** [TaiwanVtuberData/TaiwanVTuberData.github.io#110]
**錯誤項目**

 - [ ] VTuber 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [X] 頻道連結
 - [ ] 團體
 - [ ] 國家

**更正後資料**

* VTuber 名稱: 周汰南
* 活動狀態: 
* 出道日期:
* 畢業日期:
* 頻道連結: https://www.youtube.com/@amane_tainan
* 團體:
* 國家:

**佐證**

**Comment by nh60211as** [comment]
感謝回報，將於 2023/10/01 21:00 更新 YouTube 資料

**Comment by nh60211as** [comment]
Resolved
