### ISSUE TITLE
[資料登載] 天犂謬那Myuna ch.

### ISSUE THREAD

**Issue by Mao606287** [TaiwanVtuberData/TaiwanVtuberData.github.io#12]
**新人/未收錄 Vtuber 資料**

 * 名稱：天犂謬那Myuna ch.
 * YouTube 頻道連結：https://www.youtube.com/channel/UC30Dj1DKVYk4kC8iWAjKbRg/featured
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內
 - [ ] 頻道訂閱/追隨人數大於 300 
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計將於今日 (2021/12/10) 收錄。

**Comment by nh60211as** [comment]
Confirmed add at 37441f7463fa7d197ba1ec10a5d4dc8bced6652d.
