### ISSUE TITLE
[未收錄登載] 黑澤Kurosawa

### ISSUE THREAD

**Issue by Fuarei** [TaiwanVtuberData/TaiwanVTuberData.github.io#121]
**VTuber 資料**

 * 名稱：黑澤Kurosawa
 * 出道日期：2023年11月11日
 * 首次直播/影片連結：https://www.youtube.com/watch?v=5Na9k-IYJ68&ab_channel=%E9%BB%91%E6%BE%A4KurosawaCh.
 * YouTube 頻道連結：https://www.youtube.com/@kurosawaaaa
 * 國家：香港

**VTuber 目前活動狀態**

 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**VTuber 相關證明**

**Comment by nh60211as** [comment]
感謝回報，預計於 2024/03/15 06:00 收錄完整資料於
https://taiwanvtuberdata.github.io/vtuber/d78d72ce0aac4c9d9c5c16604209ced3

**Comment by nh60211as** [comment]
已確定收錄。
