### ISSUE TITLE
[未收錄登載] 皮瑞瑟Peraser

### ISSUE THREAD

**Issue by iem408171** [TaiwanVtuberData/TaiwanVTuberData.github.io#127]
**VTuber 資料**

個人勢橡皮擦Vtuber 
https://lit.link/en/Peraser
 * 名稱：皮瑞瑟Peraser
 * 出道日期：2024/04/02
 * 首次直播/影片連結：https://www.youtube.com/live/dwg2SQ-BTtw?si=4j4J6kuBUKozJ9sq
 * YouTube 頻道連結：https://www.youtube.com/@peraser1126
 * Twitch 頻道連結：https://www.twitch.tv/peraser1126
 * 所屬團體：個人
 * 國家：台灣

**VTuber 目前活動狀態**

 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**VTuber 相關證明**

https://www.youtube.com/live/dwg2SQ-BTtw?si=4j4J6kuBUKozJ9sq

**Comment by nh60211as** [comment]
感謝回報，預計將於 2024/05/09 21:00 重新收錄
個人網址：https://taiwanvtuberdata.github.io/vtuber/64bba754590e41c5b58df1c536d4e865

**Comment by nh60211as** [comment]
Resolved
