### ISSUE TITLE
[功能請求] 依出道日進行排序

### ISSUE THREAD

**Issue by FantasyDreamCK** [TaiwanVtuberData/TaiwanVTuberData.github.io#130]

**Comment by nh60211as** [comment]
已新增功能於所有 VTuber 頁面的排序方式
https://taiwanvtuberdata.github.io/all-vtubers

![圖片](https://github.com/TaiwanVtuberData/TaiwanVTuberData.github.io/assets/45863601/01de1347-3730-424e-b50f-352d8e057c45)

**Comment by nh60211as** [comment]
@FantasyDreamCK 你把你的內文打在註解裡了，因此不會顯示，請再編輯文章調整。

此功能實作於 `3.1.5` 版，請確定你的版本正確。
如果不正確，請嘗試重新整理網頁或是使用 ctrl + F5 強制重新整理網頁。

![圖片](https://github.com/TaiwanVtuberData/TaiwanVTuberData.github.io/assets/45863601/bc8bf819-ae94-4fce-a26d-f5e4021d7745)

**Comment by nh60211as** [comment]
@FantasyDreamCK 一週無回覆，關閉此 issue。
