### ISSUE TITLE
[未收錄登載] 希姆 Himusan

### ISSUE THREAD

**Issue by Himusan** [TaiwanVtuberData/TaiwanVTuberData.github.io#139]
**VTuber 資料**

 * 名稱：希姆 Himusan
 * 出道日期：
 * 首次直播/影片連結：https://www.youtube.com/live/P5bMqR8IHp0?si=yNlo76K70YtSA_US
 * YouTube 頻道連結：https://www.youtube.com/channel/UCEL-tlIkCFmPZSqSkXSJ6Zg
 * Twitch 頻道連結：
 * 所屬團體：
 * 國家：台灣

**VTuber 目前活動狀態**

 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**VTuber 相關證明**

**Comment by nh60211as** [comment]
感謝回報，已於 https://github.com/TaiwanVtuberData/TaiwanVtuberTrackingData/pull/716 收錄，預計 2024-07-30 06:00 匯入觀看數據。

**Comment by nh60211as** [comment]
確認已收錄 https://taiwanvtuberdata.github.io/vtuber/5dc565de88a948ecb092cce178aafe60
