### ISSUE TITLE
[資料錯誤] 柒玖

### ISSUE THREAD

**Issue by Mao606287** [TaiwanVtuberData/TaiwanVtuberData.github.io#14]
**錯誤項目**

 - [ ] 名稱
 - [ ] 頻道連結
 - [x] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：柒玖為社團勢 社團名：梓京 Cercis

**佐證**

2. 證明 1：https://twitter.com/Cercis_Live
![image](https://user-images.githubusercontent.com/93981768/145428405-aced2da6-874f-43d8-8de6-b6f89c86c969.png)

**Comment by nh60211as** [comment]
感謝回報。團體名稱會使用"梓京海生館"。
預計將於今日 (2021/12/10) 更新資訊。

**Comment by nh60211as** [comment]
Confirmed add at 37441f7463fa7d197ba1ec10a5d4dc8bced6652d.
