### ISSUE TITLE
[新人登載] 冬雪桜

### ISSUE THREAD

**Issue by FuyukiSakura** [TaiwanVtuberData/TaiwanVTuberData.github.io#30]
**新人 VTuber 資料**

 * 名稱：冬雪桜
 * 出道日期：2021年12月12日
 * 首次直播/影片連結：https://youtu.be/IhePAAiCla4 （圖奇直播，當時沒想到要弄成精華，只傳了YouTube，然後因為一直都是隱藏的狀態，發怖的日子就變成3月17了😭）
 * YouTube 頻道連結：https://www.youtube.com/c/FuyukiSakura/
 * Twitch 頻道連結：https://www.twitch.tv/fuyukisakura
 * 團體：
 * 國家：澳大利亞（是台灣人喇>_<）

**VTuber 目前活動狀態**

 - [ ] 出道一個月內或是尚未出道

**Comment by nh60211as** [comment]
感謝回報，頻道資訊預計將於 2022/04/09 05:55 更新。

**Comment by nh60211as** [comment]
Confirmed to be added.
