### ISSUE TITLE
[資料異動登載] Yueyu Ch. 玥語ほしぞら

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVTuberData.github.io#35]
**錯誤項目**

 - [ ] VTuber 名稱
 - [ ] 活動狀態
 - [X] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [ ] 團體
 - [ ] 國家

**更正後資料**

* 出道日期：2021/05/09 (最近只是補初配)

**Comment by nh60211as** [comment]
感謝回報，預計於下次資料更新修正。

**Comment by nh60211as** [comment]
確認已修改。
