### ISSUE TITLE
[畢業登載] 瑪格麗特．溫特斯 / Margaret．Winters 【CloudHorizon所屬】

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVTuberData.github.io#57]
**VTuber 資料**

 * 名稱：
 * 出道日期：
 * 首次直播/影片連結：
 * YouTube 頻道連結：https://www.youtube.com/channel/UCJ4VZaUiVC2vpN7TXG85M5g
 * Twitch 頻道連結：
 * 團體：雲際線工作室
 * 國家：

**VTuber 目前活動狀態**

 - [X] 三個月內畢業

**VTuber 相關證明**

https://www.youtube.com/watch?v=2V-4PclU7n8
於6月9號宣布於2022年7月9號畢業
https://zh.m.wikipedia.org/wiki/%E9%9B%B2%E9%9A%9B%E7%B7%9A%E5%B7%A5%E4%BD%9C%E5%AE%A4

**Comment by nh60211as** [comment]
感謝回報，已更新 VTuber 資訊：
https://taiwanvtuberdata.github.io/vtuber/521fb650b9534787b19c8762957fb5d2
