### ISSUE TITLE
[未收錄登載] Curio Midori 【MY Vtuber】

### ISSUE THREAD

**Issue by VanillaStar99** [TaiwanVtuberData/TaiwanVTuberData.github.io#71]
**VTuber 資料**
 * 名稱：Curio Midori
 * 出道日期：08/10/2022
 * 首次直播/影片連結：https://www.youtube.com/watch?v=qSH3HZO9dPU
 * YouTube 頻道連結：https://www.youtube.com/channel/UCv97OY_DoFrvfQcSSN3aRlw
 * Twitch 頻道連結：
 * 團體：Pasar Virtual Entertainment
 * 國家：MY

**VTuber 目前活動狀態**
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**VTuber 相關證明**

**Comment by nh60211as** [comment]
與臺灣關聯性過低，暫不收錄。
