### ISSUE TITLE
[新人登載] 雪貓yukineko

### ISSUE THREAD

**Issue by ss9104890006** [TaiwanVtuberData/TaiwanVTuberData.github.io#80]
**VTuber 資料**

 * 名稱：雪貓yukineko
 * 出道日期：4/3
 * 首次直播/影片連結：
 * YouTube 頻道連結：
 * Twitch 頻道連結：https://www.twitch.tv/yukineko1018
 * 團體：
 * 國家：TW

**VTuber 目前活動狀態**

 - [x] 出道一個月內或是尚未出道

**VTuber 相關證明**

**Comment by nh60211as** [comment]
感謝回報，待首次直播後收錄。
