### ISSUE TITLE
[功能請求] 增加對vsinger標籤的相容性支援

### ISSUE THREAD

**Issue by bigclublee** [TaiwanVtuberData/TaiwanVTuberData.github.io#99]
如題,因近期以vsinger發展的vtuber逐漸增多(如無序樂章成員)
這些vsinger已經跟vtuber無異,都有採用Live2D開歌回
但卻因為初期只有vsinger標籤而沒有vtuber標籤,因而成為列表上的遺珠之憾
故希望將vsinger標籤視為vtuber的一種

**Comment by nh60211as** [comment]
感謝建議，
改為接受有使用 Live2D 的 VSinger。
